inst/include/RcppArmadilloAs.h
inst/unitTests/cpp/cube.cpp
inst/unitTests/runit.cube.R

As discussed in #63 this extends `Rcpp::as<>` for use with Armadillo's templated `Cube` class.

Added support for conversion to arma::Cube types 

---

ChangeLog
inst/NEWS.Rd
inst/include/RcppArmadilloAs.h
inst/unitTests/cpp/sparse.cpp
inst/unitTests/runit.sparse.R

Solves issue https://github.com/RcppCore/RcppArmadillo/issues/89 as well as issue https://github.com/RcppCore/RcppArmadillo/issues/72. RcppArmadillo was compiled and checked with Valgrind and no memory leaks (or issues with `Conditional jump...`) where detected (nor in the examples, vignettes or tests). Also includes two new tests used to explicitly detect the two issues mentioned when using `R CMD check --use-valgrind`.

Fixing bug in SpMat exporter

---

ChangeLog
inst/include/RcppArmadilloExtensions/fixprob.h
inst/include/RcppArmadilloExtensions/sample.h

http://stackoverflow.com/questions/37818872/stack-imbalance-while-using-rcppparallel/37819079#37819079

Rewrote sample.h to primarily use armadillo objects instead of rcpp objects

---

ChangeLog
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparse.R

In order to solve #17 and #114. And there is a piece of codes using the algorithm from [scipy](https://github.com/scipy/scipy/blob/master/scipy/sparse/sparsetools/csr.h#L436). I have added a reference to that. What else should I do to avoid violating the copy rights? @coatless @eddelbuettel @thirdwing 
Btw, I squash and merge a branch called Rsparse to the master, but now the commit history still shows up here. I know the reason might be that I didn't squash and merge the previous commits, which leads to a messy timeline. :(

Add conversion & unit tests for dgR, dtR & dsRMatrix

---

ChangeLog
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparse.R

In order to solve #17 and #114 . Now the conversion for all the numeric sparse matrices is done. @thirdwing @eddelbuettel When doing unit tests, I found some bugs in the package Matrix. But there is only a read-only repo on the GitHub so that I cannot open a pull request. Do you have any idea where I can contribute?

Add conversion & unit tests for pMatrix & ddiMatrix

---

ChangeLog
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparseConversion.R

First, the file-based tests are based on the documentation from package Matrix, sparseM, spam, slam, SciPy.   
Second, when I did the file-based tests, I found two extreme cases that the original conversion for TsparseMatrix cannot satisfy, so I rewrite the conversion.
The two new cases include:
1. [i is increasingly ordered](https://github.com/binxiangni/RcppArmadillo/blob/master/tests/testSparse.R#L183);
2. [(i, j) pair is repeated](https://github.com/binxiangni/RcppArmadillo/blob/master/tests/testSparse.R#L46).
Last, I've passed the tests, but there is a warning that 
`Warning in read_symbols_from_dll(so, rarch) :`
`this requires 'objdump.exe' to be on the PATH`
Should I do something?

Rewrite conversion for dgT, dtT & dsTMatrix & add file-based tests

---

ChangeLog
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparse.R
inst/unitTests/runit.sparseConversion.R

This is the last numeric sparse matrix left. So far the conversion for the numeric sparse matrix should be done.

Add conversion & unit tests for indMatrix

---

ChangeLog
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparseConversion.R

Although just adding the warning message can pass the tests, it will not stop the program and provide a wrong result. Should I replace `Rcpp::warning()` with `Rcpp::stop()`?

Add a warning message for matrices that cannot be converted

---

vignettes/RcppArmadillo-sparseMatrix.Rnw

@binxiangni I updated the vignette a little, see a [(temp) copy of the pdf](http://dirk.eddelbuettel.com/tmp/RcppArmadillo-sparseMatrix.pdf) for a quick glance.

use Rcpp vignette style

---

R/unit.test.R
inst/include/RcppArmadilloWrap.h
inst/unitTests/cpp/any_as_vec.cpp
inst/unitTests/cpp/armadillo.cpp
inst/unitTests/cpp/colrow_as_vec.cpp
inst/unitTests/runit.RcppArmadillo.R

I don't know how to add unit tests with RUnit so tested by hand with code snipets like the following:
```r
> sourceCpp(code="// [[Rcpp::depends(RcppArmadillo)]]\n#include <RcppArmadillo.h>\n// [[Rcpp::export]]\narma::vec add1(arma::vec x) {return(x+1);}")
> add1(1:2)
[,1]
[1,]    2
[2,]    3
```
```r
> sourceCpp(code="// [[Rcpp::depends(RcppArmadillo)]]\n#define RCPP_ARMADILLO_RETURN_COLVEC_AS_VECTOR\n#include <RcppArmadillo.h>\n// [[Rcpp::export]]\narma::vec add1v(arma::vec x) {return(x+1);}")
> add1v(1:2)
[1] 2 3
```
```r
> sourceCpp(code="// [[Rcpp::depends(RcppArmadillo)]]\n#define RCPP_ARMADILLO_RETURN_ANYVEC_AS_VECTOR\n#include <RcppArmadillo.h>\n// [[Rcpp::export]]\narma::vec add1v(arma::vec x) {return(x+1);}")
> add1v(1:2)
[1] 2 3
```
```r
> sourceCpp(code="// …
```

added optional RCPP_ARMADILLO_RETURN_COLVEC_AS_VECTOR and co.

---

inst/include/armadillo_bits/SpMat_meat.hpp
inst/unitTests/cpp/sparse.cpp
inst/unitTests/runit.sparse.R

__Please don't merge this. I need to double check the definition of slot "p" and "col_ptrs".__
Before this PR:
```cpp
#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]
//
using namespace Rcpp;
using namespace arma;
//[[Rcpp::export]]
sp_mat test() {
return speye(4, 5);
}
/*
> Rcpp::sourceCpp("test.cpp")
> library(Matrix)
> test()
4 x 5 sparse Matrix of class "dgCMatrix"
Error in validObject(x) : 
invalid class “dgCMatrix” object: slot p must be non-decreasing
*/
```
Now:
```r
> Rcpp::sourceCpp("test.cpp")
> library(Matrix)
> test()
4 x 5 sparse Matrix of class "dgCMatrix"
[1,] 1 . . . .
[2,] . 1 . . .
[3,] . . 1 . .
[4,] . . . 1 .
```

Fix the problem in slot "p" in "dgCMatrix". close #149

---

DESCRIPTION
inst/include/RcppArmadilloAs.h
inst/unitTests/runit.sparseConversion.R

A small patch adding conversion of simple_triplet_matrix format from package slam.
Sorry for all these white spaces removing, it's my new editor Atom who's responsible.
If it's too annoying for you, I'll try to disable this feature and submit with only pertinent part of
modifications.

conversion of simple_triplet_matrix

---

inst/unitTests/cpp/Rlapack.cpp
inst/unitTests/runit.Rlapack.R

Add a unit test for complex-valued matrix decompositions. These tests are designed to trigger Lapack routines that were added to Rlapack in R versions 3.1.0 and 3.3.0.
RcppCore/RcppArmadillo/issues/207

Add Rlapack unit test

---

R/SciPy2R.R
configure
configure.ac
inst/unitTests/runit.scipy2r.R

Addresses #224. On a macOS system using gcc7:
```
* installing *source* package ‘RcppArmadillo’ ...
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++-mp-7 accepts -g... yes
checking how to run the C++ preprocessor... g++-mp-7 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++-mp-7 accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 7.3.0
checking for macOS... found
checking for macOS Apple compiler... not found
checking for clang compiler... not …
```

add warning for nonstandard macOS builds

---

R/RcppArmadillo.package.skeleton.R

Enable use of `example_code = FALSE` argument in `RcppArmadillo.package.skeleton()` when `pkgKitten` is installed.

Fixes #229

---

configure
configure.ac

The `test` command, as well as the `[` command, is not required to
know the `==` operator. Only a few implementations like bash and some
versions of ksh support it.
When you run `test foo == foo` on a platform that does not support the
`==` operator, the result will be false instead of true. This can lead
to unexpected behavior.

Portability fixes for configure

---

ChangeLog
inst/include/RcppArmadilloForward.h

Related to bug https://github.com/RcppCore/RcppArmadillo/issues/314
change `#include <armadillo>` to `#include "armadillo"`

use quotes instead of angle brackets to include armadillo header

---

ChangeLog
R/RcppExports.R
inst/tinytest/test_sparseConversion.R

The coercion from ddi matrix to dgC matrix, e.g. `as(ddi_matrix, "dgCMatrix")`,  does not work as before, and its output is dtC matrix instead of dgC matrix.  So I have coerce again from dtC matrix to dgC matrix.

Fix the unit test error from converting ddi matrix to dgC matrix

---

inst/include/RcppArmadilloForward.h
inst/include/RcppArmadilloWrap.h

- add handling of subview_cols<T>
- speedup in handling subview<T>: since the size is known, use .at() to skip unnecessary bounds checks

handle subview_cols in Armadillo 10.7

---

inst/include/RcppArmadilloAs.h
inst/include/RcppArmadilloConfig.h
inst/include/RcppArmadilloWrap.h
inst/tinytest/test_rcpparmadillo.R
src/RcppExports.cpp

Attempts to fix https://github.com/RcppCore/RcppArmadillo/issues/351
This correctly passes the dims of nested lists when arma::field is specified as input (so field from R to Cpp).
This implementation works with 1d and 2d fields. The generalization to 3d seems very straightforward. However, just adding a third loop and extending the dims results in an error at runtime:  "product [x] do not match the length of object [x]".
This problem with 3d arrays most probably also affects "FieldImporter" (so field from C++ to R) since the following function fails with the same error:
```
#include <RcppArmadillo.h>
using namespace arma;
// [[Rcpp::export]]
field<mat> fieldtest1()
{
field<mat> out(5, 5, 5);
return out;
}
```

Fix dim problem with arma::field inputs

---

ChangeLog
configure
configure.ac

With thanks to @jsilve24 for identifying the issue and suggesting a fix (also in #376).  Credit will go into NEWS.Rd too.

Ensure openmp propagates in the 'found' case (closes #375)

---

ChangeLog
src/Makevars.in

Fixes the underlying issue in https://github.com/RcppCore/RcppArmadillo/issues/406. With this, the compiler invocation when building on macOS is (for example):
```
clang++ -mmacosx-version-min=10.13 -std=gnu++14 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Users/kevin/Library/R/x86_64/4.2/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppArmadillo.cpp -o RcppArmadillo.o
< ... >
```
And because `-I../inst/include` is now coming before `-I/usr/local/include`, we should now be able to avoid issues where a system installation of Armadillo in `/usr/local/include` takes precedence over the bundled version.

set includes in PKG_CPPFLAGS

---

ChangeLog
inst/include/RcppArmadillo/interface/RcppArmadilloAs.h

Finally got around to working on this.  A few comments:
* Perhaps verify that I haven't introduced whitespace issues. I noticed that my Emacs inserted tabs where the file otherwise had none.  Well, I fixed whatever I saw ...
* Unrelated to the issue, I replaced 5 lines of code repeated throughout the file with a macro.  It was too upsetting ...
* I noticed that in several places you have `ncol + 1`, where `ncol` is an `int`.  Note that `ncol` may take the value `INT_MAX` and in that case `ncol + 1` will overflow.  The patch does not attempt to address this.
* I've used `R_alloc` somewhere, but maybe that is not idiomatic ... I needed to do `a[i]++` and did not feel like checking whether that was legal for `a` of type `IntegerVector` rather than `int *` ...

Accomodate upcoming change in package Matrix (fixes #415)

---

inst/CITATION

@eddelbuettel  The peer-reviewed article should be cited before the manual.  Detailed reasoning given in email.

Swap order of the two bibentry instances

---

inst/include/current/armadillo_bits/diskio_bones.hpp
inst/include/current/armadillo_bits/diskio_meat.hpp
inst/include/current/armadillo_bits/glue_hist_meat.hpp

Sync with Armadillo upstream
